Update to work with latest portability drivers https://github.com/KhronosGroup/Vulkan-Loader/pull/924
Fixes:
2023-01-10 19:06:40.981597+0000 HelloTriangle[45030:5632266] Metal API Validation Enabled
WARNING: Requested layer VK_LAYER_LUNARG_monitor is not supported. It will not be enabled.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
GENERAL+ERROR: [Instance(0x10301E800)]: Loader Message(0), "vkCreateInstance: Found drivers that contain devices which support the portability subset, but the portability enumeration bit was not set! Applications that wish to enumerate portability drivers must set the VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR bit in the VkInstanceCreateInfo flags and enable the VK_KHR_portability_enumeration instance extension."
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
GENERAL+ERROR: [Instance(0x10301E800)]: Loader Message(0), "vkCreateInstance: Found no drivers!"
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

ERROR: Terminated due to an uncaught VkResult exception: /Users/raafat/github/Hello_Triangle/src/HelloTriangle.cpp:750:initInstance() vkCreateInstance() returned VK_ERROR_INCOMPATIBLE_DRIVER
Program ended with exit code: 1